# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
    ]
